spring:
  cache:
    type: redis
    redis:
      time-to-live: 1800000ms
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    username: root
    password: '123456789a'
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/media?characterEncoding=utf-8&useSSL=false
    hikari:
      connection-init-sql: SET NAMES utf8mb4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    username: 837447352@qq.com
    password: tbtshyehhponbbfa
    default-encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    # password: justdoit
    port: 6379
tengxun:
  accessKey: AKIDyiCPL6jpmSjkVzHZS4Q3RZQEn7AwpkjT
  secretKey: hCTXcS1JK6ez7CRP6WgmcClGVVDjz2pd
  bucket: ap-shanghai
  bucketName: zone-1253231183
  path: https://zone-1253231183.cos.ap-shanghai.myqcloud.com
mail:
  activateUrl: http://localhost/userActive.html?